import type { CommentTarget, DocumentView, JsonValue, ReviewComment, ReviewDecision } from '../../contracts';
import { Button } from '@/components/ui/button';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from '@/components/ui/select';

export const decisionNames = {pending: '미검토', approve: '승인', request_changes: '수정 요청'};
const kindNames = {change_request: '수정 요청', question: '질문', note: '참고'};
export interface CommentInput {body: string; kind: ReviewComment['kind']; blocking: boolean; target: CommentTarget}
export function newCommentInput(objectId: string): CommentInput {return {body: '', kind: 'question', blocking: false, target: {object_id: objectId, element_id: null, field: null, operation_id: null, pointer: null}};}
function record(value: JsonValue): value is {[key: string]: JsonValue} {return value !== null && typeof value === 'object' && !Array.isArray(value);}
function targetOptions(view: DocumentView | undefined, objectId: string) {
  const base = newCommentInput(objectId).target;
  const options = [{value: 'document', label: '문서 전체', target: base, content: view?.content as JsonValue | undefined}];
  if (!view) return options;
  for (const [key, value] of Object.entries(view.content)) if (Array.isArray(value)) for (const element of value) if (record(element) && typeof element.id === 'string') options.push({value: 'element:' + element.id, label: key + ' · ' + element.id, target: {...base, element_id: element.id}, content: element});
  if (view.projection.kind === 'openapi') for (const operation of view.projection.operations) options.push({value: 'operation:' + operation.operation_id, label: operation.method.toUpperCase() + ' ' + operation.path + ' · ' + operation.operation_id, target: {...base, operation_id: operation.operation_id}, content: operation.content});
  return options;
}
export function Judgment({value, disabled, onChange}: {value: ReviewDecision; disabled: boolean; onChange: (value: ReviewDecision) => void}) {
  return <Field><FieldLabel htmlFor="item-decision">이 항목의 판단</FieldLabel><Select value={value.decision} disabled={disabled} onValueChange={decision => onChange({...value, decision: decision as ReviewDecision['decision']})}><SelectTrigger id="item-decision"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{Object.entries(decisionNames).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>;
}
export function Comments({value, input, view, objectId, disabled, onInput, onChange}: {value: ReviewDecision; input: CommentInput; view?: DocumentView; objectId: string; disabled: boolean; onInput: (value: CommentInput) => void; onChange: (value: ReviewDecision) => void}) {
  const options = targetOptions(view, objectId);
  const selected = input.target.element_id ? 'element:' + input.target.element_id : input.target.operation_id ? 'operation:' + input.target.operation_id : 'document';
  const content = options.find(option => option.value === selected)?.content;
  const fields = content && record(content) ? Object.keys(content) : [];
  const changeComment = (index: number, update: Partial<ReviewComment>) => onChange({...value, comments: value.comments.map((comment, current) => current === index ? {...comment, ...update} : comment)});
  return <Collapsible><CollapsibleTrigger asChild><Button variant="outline">댓글과 대상 ({value.comments.length})</Button></CollapsibleTrigger><CollapsibleContent className="mt-4"><div className="flex flex-col gap-6">
    {value.comments.map((comment, index) => <section key={comment.id} className="flex flex-col gap-3 border-b pb-4"><p className="break-all text-sm">{kindNames[comment.kind]} · {comment.target.element_id ?? comment.target.operation_id ?? comment.target.object_id}{comment.target.field ? ' · ' + comment.target.field : ''}{comment.target.pointer ? ' · ' + comment.target.pointer : ''}</p><Field><FieldLabel htmlFor={'comment-' + comment.id}>저장할 댓글 {index + 1}</FieldLabel><Textarea id={'comment-' + comment.id} disabled={disabled} value={comment.body} onChange={event => changeComment(index, {body: event.target.value})} /></Field><Field orientation="horizontal"><Checkbox id={'blocking-' + comment.id} checked={comment.blocking} disabled={disabled} onCheckedChange={checked => changeComment(index, {blocking: checked === true})} /><FieldLabel htmlFor={'blocking-' + comment.id}>해결 전 승인 차단</FieldLabel></Field>{!disabled && <Button variant="ghost" size="sm" onClick={() => onChange({...value, comments: value.comments.filter(item => item.id !== comment.id)})}>댓글 삭제</Button>}</section>)}
    {(!disabled || input.body.trim()) && <FieldGroup><h3 className="font-semibold">댓글 작성</h3><Field><FieldLabel htmlFor="comment-body">새 댓글</FieldLabel><Textarea id="comment-body" disabled={disabled} value={input.body} onChange={event => onInput({...input, body: event.target.value})} /></Field><p className="text-sm text-muted-foreground">작성 중인 댓글은 ‘댓글 추가’ 후 자동 저장됩니다.</p><Field><FieldLabel htmlFor="comment-kind">분류</FieldLabel><Select disabled={disabled} value={input.kind} onValueChange={kind => onInput({...input, kind: kind as ReviewComment['kind']})}><SelectTrigger id="comment-kind"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{Object.entries(kindNames).map(([key, name]) => <SelectItem key={key} value={key}>{name}</SelectItem>)}</SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="comment-target">안정된 대상</FieldLabel><Select disabled={disabled} value={selected} onValueChange={key => onInput({...input, target: options.find(option => option.value === key)!.target})}><SelectTrigger id="comment-target"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{options.map((option, index) => <SelectItem key={option.value + index} value={option.value}>{option.label}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>{objectId !== 'scope:implementation' && <><Field><FieldLabel htmlFor="comment-field">대상의 필드</FieldLabel><Select disabled={disabled} value={input.target.field === null ? 'whole' : 'field:' + input.target.field} onValueChange={field => onInput({...input, target: {...input.target, field: field === 'whole' ? null : field.slice(6)}})}><SelectTrigger id="comment-field"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="whole">대상 전체</SelectItem>{fields.map(field => <SelectItem key={field} value={'field:' + field}>{field}</SelectItem>)}</SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="comment-pointer">세부 JSON Pointer (선택)</FieldLabel><Input id="comment-pointer" disabled={disabled} value={input.target.pointer ?? ''} placeholder="/paths/~1messages/post/summary" onChange={event => onInput({...input, target: {...input.target, pointer: event.target.value || null}})} /></Field></>}
    <Field orientation="horizontal"><Checkbox id="new-comment-blocking" disabled={disabled} checked={input.blocking} onCheckedChange={checked => onInput({...input, blocking: checked === true})} /><FieldLabel htmlFor="new-comment-blocking">해결 전 승인 차단</FieldLabel></Field><Button variant="outline" disabled={disabled || !input.body.trim()} onClick={() => {onChange({...value, comments: [...value.comments, {...input, id: crypto.randomUUID()}]}); onInput(newCommentInput(objectId));}}>댓글 추가</Button></FieldGroup>}
  </div></CollapsibleContent></Collapsible>;
}
